// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maexmjznkjfgzzcebchp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZXhtanpua2pmZ3p6Y2ViY2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzEwNzAsImV4cCI6MjA2NTU0NzA3MH0.lJTvMpCj3dhv4F513OPGX6gjd4QhCm7eLHVvBc5FqT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);